// Slovak -> English phrases applied to rendered text by lib/i18n/dom-translator.ts.
// Keys must match the rendered Slovak text exactly (whitespace is trimmed).
export const uiTranslations: Record<string, string> = {
  // Regions, levels, hands
  'Bratislavský kraj': 'Bratislava Region', 'Trnavský kraj': 'Trnava Region', 'Trenčiansky kraj': 'Trenčín Region', 'Nitriansky kraj': 'Nitra Region', 'Žilinský kraj': 'Žilina Region', 'Banskobystrický kraj': 'Banská Bystrica Region', 'Prešovský kraj': 'Prešov Region', 'Košický kraj': 'Košice Region',
  'Bratislavský': 'Bratislava', 'Trnavský': 'Trnava', 'Trenčiansky': 'Trenčín', 'Nitriansky': 'Nitra', 'Žilinský': 'Žilina', 'Banskobystrický': 'Banská Bystrica', 'Prešovský': 'Prešov', 'Košický': 'Košice',
  'Celé Slovensko': 'All of Slovakia', 'Začiatočník': 'Beginner', 'Začiatočníci': 'Beginners', 'Mierne pokročilý': 'Intermediate', 'Mierne pokročilí': 'Intermediate', 'Pokročilý': 'Advanced', 'Profesionál': 'Professional', 'Expert': 'Expert',
  'Pravák': 'Right-handed', 'Ľavák': 'Left-handed', 'Hráš oboma rukami': 'Ambidextrous',

  // Navigation, shared
  'Prehľad': 'Overview', 'Môj profil': 'My profile', 'Rebríčky': 'Rankings', 'Nájsť hráčov': 'Find players', 'Nájsť súperov': 'Find opponents', 'Vyzvať dvojicu': 'Challenge a pair', 'Zápasy': 'Matches', 'Turnaje': 'Tournaments', 'Arény': 'Arenas', 'Správy': 'Messages', 'Nastavenia': 'Settings', 'Profil': 'Profile',
  'MÔJ PROFIL': 'MY PROFILE', 'DVOJICE': 'PAIRS', 'VYZVAŤ DVOJICU': 'CHALLENGE A PAIR', 'ZÁPASY': 'MATCHES', 'ARÉNY': 'ARENAS', 'SPRÁVY': 'MESSAGES', 'NASTAVENIA': 'SETTINGS', 'NÁJSŤ HRÁČOV': 'FIND PLAYERS', 'REBRÍČKY': 'RANKINGS', 'TURNAJE': 'TOURNAMENTS', 'PREHĽAD': 'OVERVIEW',
  'Ako to funguje': 'How it works', 'Prihlásiť sa': 'Log in', 'Registrovať sa': 'Sign up', 'Odhlásiť sa': 'Log out', 'Zavrieť': 'Close', 'Zavrieť menu': 'Close menu', 'Otvoriť menu': 'Open menu', 'Zavrieť navigáciu': 'Close navigation', 'Hlavná navigácia': 'Main navigation', 'Mobilná navigácia': 'Mobile navigation', 'SPL domov': 'SPL home', 'SPL — Prehľad': 'SPL — Overview', 'Viac aktivít': 'More activity',
  'Zrušiť': 'Cancel', 'Odoslať': 'Send', 'Vytvoriť': 'Create', 'Uložiť zmeny': 'Save changes', 'Späť': 'Back', '← Späť': '← Back', '← Späť na prehľad': '← Back to overview', 'Späť na prehľad': 'Back to overview', 'Skúsiť znova': 'Try again', 'Vyzvať': 'Challenge', 'Vyzvať na zápas': 'Challenge to a match', 'Správa': 'Message', 'Zobraziť profil': 'View profile', 'Profil hráča': 'Player profile', 'Tvoj profil': 'Your profile',

  // Landing / how it works
  'Slovak Padel League je celoslovenská liga hráčov v padeli. Zbieraj body, zlepšuj svoj rebríček, vyzývaj súperov a hraj o skvelé ceny.': 'Slovak Padel League is a nationwide padel league. Earn points, climb the rankings, challenge opponents and play for great prizes.',
  'Hraj.': 'Play.', 'Vyzývaj.': 'Challenge.', 'Zlepšuj sa.': 'Improve.', 'Staň sa najlepším.': 'Become the best.', 'Stať sa členom': 'Join the league', 'Slovenská padelová liga': 'Slovak padel league',
  'Viac zápasov.': 'More matches.', 'Lepší hráč.': 'Better player.', 'SPL spája hráčov, arény a súťaživý padel do jednej férovej komunity.': 'SPL brings players, arenas and competitive padel together in one fair community.', 'Registrovať sa a začať hrať': 'Sign up and start playing',
  'Celoslovenská komunitná sieť': 'Nationwide community network', 'Prepoj sa s hráčmi a padelovými arénami po celom Slovensku. Vyzývaj súperov v ľubovoľnom kraji bez ohľadu na úroveň.': 'Connect with players and padel arenas across Slovakia. Challenge opponents in any region regardless of level.',
  'Dynamický ELO rating': 'Dynamic ELO rating', 'Každý overený zápas mení tvoju pozíciu v rebríčku. Výhra pridá body, prehra ich odoberie podľa sily súpera.': 'Every verified match changes your ranking position. A win adds points, a loss removes them depending on the strength of your opponent.',
  '6-mesačné sezóny': '6-month seasons', 'Hraj v pravidelných ligových cykloch. Top 3 hráči celoštátneho aj krajského rebríčka získajú ocenenia.': 'Play in regular league cycles. The top 3 players of both the national and regional rankings receive awards.',
  'Oficiálne SPL turnaje': 'Official SPL tournaments', 'Zúčastni sa pravidelných turnajov, získaj špeciálne ocenenia a bonusové body za víťazstvo.': 'Take part in regular tournaments, earn special awards and bonus points for winning.',
  'Férové overenie výsledkov': 'Fair result verification', 'Výsledok zapíše jedna dvojica a druhá ho potvrdí priamo v aplikácii. Body sa pripíšu až po obojstrannom schválení.': 'One pair enters the result and the other confirms it right in the app. Points are awarded only after both sides approve.',

  // Auth
  'PRIHLÁSENIE': 'LOG IN', 'REGISTRÁCIA': 'SIGN UP', 'Heslo': 'Password', 'Nové heslo': 'New password', 'Potvrď heslo': 'Confirm password', 'Meno': 'Name', 'Kraj': 'Region', 'Úroveň hráča': 'Player level', 'Vyber úroveň': 'Select level', 'Vyber svoj kraj': 'Select your region', 'Dominantná ruka': 'Dominant hand', 'Domovská aréna': 'Home arena', 'Vyber domovskú arénu': 'Select home arena',
  'Domovský klub sa automaticky upraví podľa najnavštevovanejšieho klubu.': 'Your home club is automatically updated based on the club you visit most.', 'Zoznam arén sa nepodarilo načítať.': 'Could not load the list of arenas.',
  'PRIHLÁSIŤ SA': 'LOG IN', 'PRIHLASUJEM...': 'LOGGING IN...', 'REGISTROVAŤ SA': 'SIGN UP', 'REGISTRUJEM...': 'SIGNING UP...', 'Nemáš účet?': "Don't have an account?", 'Zadaj svoje meno': 'Enter your name', 'vas@email.sk': 'you@email.com',
  'Nesprávny email alebo heslo.': 'Incorrect email or password.', 'Heslá sa nezhodujú.': 'Passwords do not match.', 'Prihlásenie sa nepodarilo uskutočniť.': 'Login failed.', 'Registráciu sa nepodarilo uskutočniť': 'Sign-up failed',
  'Obnova hesla': 'Password reset', 'Ak účet s týmto e-mailom existuje, poslali sme ti odkaz na obnovu hesla.': 'If an account with this email exists, we have sent you a password reset link.', 'Späť na Prihlásenie': 'Back to Log in', 'Odoslanie odkazu sa nepodarilo. Skontroluj e-mail a skús to znova.': 'Could not send the link. Check your email and try again.', 'ODOSIELAM...': 'SENDING...', 'POSLAŤ ODKAZ': 'SEND LINK',
  'SPL účet': 'SPL account', 'Skontroluj svoj email': 'Check your email', 'Poslali sme ti potvrdzovací odkaz. Po potvrdení emailu bude tvoj hráčsky profil automaticky zaradený do rebríčka.': 'We have sent you a confirmation link. Once you confirm your email, your player profile will be added to the rankings automatically.', 'Späť na úvod': 'Back to start',
  'Heslo bolo zmenené.': 'Your password has been changed.', 'ZMENIŤ HESLO': 'CHANGE PASSWORD', 'Heslo musí mať aspoň 8 znakov a jednu číslicu.': 'Password must have at least 8 characters and one digit.', 'Heslo sa nepodarilo zmeniť. Skús odkaz obnovy znova.': 'Could not change the password. Try the reset link again.',

  // Overview
  'Zatiaľ žiadne naplánované zápasy': 'No scheduled matches yet', 'Prijmi výzvu od hráča alebo vytvor nový zápas.': 'Accept a challenge from a player or create a new match.', 'Zatiaľ bez zápasov': 'No matches yet', 'Tvoja história zápasov sa zobrazí tu.': 'Your match history will appear here.', 'Výzvy': 'Challenges', 'Zadať výsledok': 'Enter result',

  // Settings
  'Hráčsky profil & údaje': 'Player profile & details', 'Notifikácie & upozornenia': 'Notifications & alerts', 'Súkromie & viditeľnosť': 'Privacy & visibility', 'Kluby & dostupnosť': 'Clubs & availability', 'Zabezpečenie & účet': 'Security & account',
  'Zobrazované meno': 'Display name', 'Telefónne číslo': 'Phone number', 'Krátky profilový popis / Bio': 'Short profile bio',
  'Nová prijatá výzva od hráča': 'New challenge received from a player', 'Nová súkromná správa v čate': 'New private chat message', 'Pozvánky na turnaje a ligové novinky': 'Tournament invitations and league news',
  'Telefónne číslo súperom': 'Phone number visible to opponents', 'Zobraziť všetkým': 'Show to everyone', 'Len po prijatí výzvy': 'Only after a challenge is accepted', 'Nikdy': 'Never', 'Zobraziť štatistiky a históriu zápasov verejne': 'Show stats and match history publicly', 'Povoliť priame správy od hráčov mimo mojej úrovne': 'Allow direct messages from players outside my level',
  'Môj domovský klub': 'My home club', 'Časová dostupnosť na zápasy': 'Availability for matches', 'Pracovné dni': 'Weekdays', 'Víkendy': 'Weekends', 'Na dni nezáleží': 'Any day',
  'Aktuálne heslo': 'Current password', 'Potvrdenie nového hesla': 'Confirm new password', 'Zmeniť heslo': 'Change password', 'Červená zóna': 'Danger zone', 'Deaktivácia alebo trvalé vymazanie účtu a všetkých dát.': 'Deactivate or permanently delete your account and all data.', 'Deaktivovať účet': 'Deactivate account', 'Vymazať účet a dáta': 'Delete account and data',
  'Nastavenia boli úspešne uložené': 'Settings saved successfully', 'Vymazať účet a dáta?': 'Delete account and data?', 'Táto akcia je trvalá a nedá sa vrátiť späť. V demo režime iba zatvorí toto potvrdenie.': 'This action is permanent and cannot be undone. In demo mode it only closes this confirmation.', 'Potvrdiť vymazanie': 'Confirm deletion',
  'Slovenčina': 'Slovak', 'Profil sa nepodarilo uložiť.': 'Could not save the profile.',

  // Opponents / find players
  'Nájdi dostupných hráčov vo tvojom kraji na ligový alebo priateľský zápas.': 'Find available players in your region for a league or friendly match.', 'Hľadať hráča...': 'Search player...', 'Hľadať hráča': 'Search player', 'Všetky úrovne': 'All levels', 'Všetky dostupnosti': 'All availability', 'Dostupnosť': 'Availability', 'Večer': 'Evening', 'Dostupný:': 'Available:',
  'Zatiaľ tu nie sú dostupní súperi': 'No available opponents yet', 'Keď sa zaregistrujú hráči v tomto kraji, zobrazia sa tu automaticky.': 'When players register in this region, they will appear here automatically.',
  'Pridať do priateľov': 'Add as friend', 'Žiadosť odoslaná': 'Request sent', 'Prijať žiadosť o priateľstvo': 'Accept friend request', 'Priatelia': 'Friends', 'Telefón': 'Phone', 'Skryté – zobrazí sa po prijatí výzvy': 'Hidden – shown after an accepted challenge', 'Akciu sa nepodarilo dokončiť.': 'The action could not be completed.',
  'Hľadať podľa mena': 'Search by name', 'Všetky kraje': 'All regions', 'Úroveň': 'Level', 'Zrušiť filtre': 'Clear filters', 'Načítavam hráčov…': 'Loading players…', 'ELO od': 'ELO from', 'ELO do': 'ELO to', 'Nájdení hráči': 'Players found', 'Hráčov sa nepodarilo načítať.': 'Could not load players.', 'Zatiaľ žiadni hráči': 'No players yet', 'Filtrom nezodpovedá žiadny hráč': 'No player matches the filters', 'Keď sa do ligy zaregistrujú ďalší hráči, nájdeš ich tu.': 'When more players join the league, you will find them here.', 'Skús upraviť vyhľadávanie alebo rozsah ELO.': 'Try adjusting the search or the ELO range.', 'Kraj neuvedený': 'Region not specified', 'Úroveň neuvedená': 'Level not specified', 'Nenašli sa žiadni hráči s vybranými filtrami.': 'No players found with the selected filters.',

  // Matchmaking / listings
  'SPL / HRÁČI': 'SPL / PLAYERS', 'Padel Matchmaking': 'Padel Matchmaking', 'Inzeráty': 'Listings', 'Burza hráčov': 'Player exchange', 'Pozrieť inzeráty →': 'View listings →', 'Inzeráty hráčov': 'Player listings', '+ Vytvoriť inzerát': '+ Create listing', 'Vytvoriť inzerát': 'Create listing', 'Inzeráty & výzvy': 'Listings & challenges', 'Vyhľadaj hráčov ligy SPL alebo pozri aktívne inzeráty.': 'Search SPL league players or browse active listings.',
  'Filtrovať podľa kraja': 'Filter by region', 'Filtrovať podľa úrovne': 'Filter by level', 'Úroveň vyzývateľa': 'Challenger level', 'Úroveň vyzývateľa:': 'Challenger level:', 'Načítavam inzeráty…': 'Loading listings…', 'Reagovať správou': 'Reply with a message', 'Zatiaľ tu nie sú žiadne aktívne inzeráty.': 'There are no active listings yet.', 'Nový inzerát': 'New listing', 'Nový inzerát / výzva': 'New listing / challenge', 'Typ inzerátu': 'Listing type', 'Vyber kraj': 'Select region',
  'Dátum (voliteľné)': 'Date (optional)', 'Čas (voliteľné)': 'Time (optional)', 'Poznámka': 'Note', 'Reagovať na inzerát': 'Reply to listing', 'Posielaš správu používateľovi:': 'You are messaging user:', 'Potrebujeme jedného hráča': 'We need one player', 'Potrebujeme dvoch hráčov': 'We need two players', 'Potrebujeme troch hráčov': 'We need three players',
  'Údaje sa nepodarilo načítať.': 'Could not load data.', 'Musíš byť prihlásený!': 'You must be logged in!', 'Správa bola úspešne odoslaná do schránky!': 'Message sent successfully!', 'Správa bola úspešne odoslaná.': 'Message sent successfully.', 'Neznámy hráč': 'Unknown player', 'Nezadaný': 'Not specified', 'Nezadaná': 'Not specified', 'Neuvedená': 'Not specified', 'Neuvedené': 'Not specified', 'Neznámy': 'Unknown', 'Neuvedená v profile': 'Not specified in profile', 'Matchmaking': 'Matchmaking',
  'Zadaj meno hráča': 'Enter player name', 'Hráme v utorok o 18:00…': 'We are playing on Tuesday at 18:00…', 'Napíš svoju správu…': 'Write your message…', 'Minimálne ELO:': 'Minimum ELO:', 'Maximálne ELO:': 'Maximum ELO:', 'Kraj:': 'Region:', 'Úroveň:': 'Level:', 'ELO:': 'ELO:', 'Termín:': 'Date:', 'Autor:': 'Author:', 'Zapojení hráči:': 'Players involved:', 'Profil prihláseného používateľa sa nenašiel.': 'The logged-in user profile was not found.', 'Pri zadaní času vyber aj dátum.': 'Select a date when entering a time.', 'Inzerát sa nepodarilo vytvoriť.': 'Could not create the listing.', 'Inzeráty sa nepodarilo načítať.': 'Could not load listings.', 'Odoslanie správy zlyhalo:': 'Sending the message failed:',

  // Messages / friends
  'Komunikuj so spoluhráčmi a súpermi.': 'Communicate with teammates and opponents.', 'Osobné správy': 'Direct messages', 'Ligové notifikácie': 'League notifications', 'Žiadosti o priateľstvo': 'Friend requests', 'Prijať': 'Accept', 'Odmietnuť': 'Decline', 'Tento hráč ešte nie je tvoj priateľ. Pridaj ho z jeho profilu v „Nájsť hráčov“.': 'This player is not your friend yet. Add them from their profile in “Find players”.', 'Načítavam priateľov…': 'Loading friends…', 'Zatiaľ nemáš žiadnych priateľov': "You don't have any friends yet", 'Pridaj hráča do priateľov z jeho profilu v „Nájsť hráčov“. Po prijatí žiadosti si môžete písať.': 'Add a player as a friend from their profile in “Find players”. Once the request is accepted you can chat.', 'Vyber priateľa zo zoznamu.': 'Select a friend from the list.', 'Začni konverzáciu správou.': 'Start the conversation with a message.', 'Napíš správu...': 'Write a message...',
  'Žiadosť sa nepodarilo spracovať.': 'Could not process the request.', 'Priateľov sa nepodarilo načítať.': 'Could not load friends.', 'Správu sa nepodarilo odoslať.': 'Could not send the message.', 'Správy sa nepodarilo načítať.': 'Could not load messages.', 'Nová žiadosť o priateľstvo': 'New friend request', 'Neplatné ID hráča.': 'Invalid player ID.', 'Nemôžeš pridať sám seba.': 'You cannot add yourself.',
  'Zatiaľ nemáš žiadne ligové notifikácie': 'No league notifications yet', 'Keď ti niekto pošle výzvu alebo správu, zobrazí sa tu.': 'When someone sends you a challenge or a message, it will appear here.',

  // Matches
  'Spravuj výsledky, schválenia a zápasovú históriu.': 'Manage results, approvals and match history.', 'Čakajúce na schválenie': 'Pending approval', 'Schválené zápasy': 'Approved matches', 'Sporné / Nahlásené': 'Disputed / Reported', 'Zatiaľ nemáš žiadne odohraté ani čakajúce zápasy': 'You have no played or pending matches yet', 'Po odohraní zápasu zadaj výsledok a po schválení sa zapíšu presné štatistiky do profilu.': 'After playing a match, enter the result and once approved the exact statistics are added to your profile.',
  'Potvrdiť skóre': 'Confirm score', 'Nahlásiť nesprávne skóre': 'Report incorrect score', 'Čaká na potvrdenie': 'Awaiting confirmation', 'POTVRDENÝ': 'CONFIRMED', 'ROZPOR V SKÓRE': 'SCORE DISPUTE', 'Zadať výsledok zápasu': 'Enter match result', 'Dátum & čas': 'Date & time', 'Aréna': 'Arena', 'Súper': 'Opponent', 'Typ zápasu': 'Match type', 'Ligový ELO zápas': 'League ELO match', 'Priateľský': 'Friendly', 'Priateľský zápas': 'Friendly match', 'Odoslať na schválenie': 'Submit for approval',
  'Set 1 — hráč 1': 'Set 1 — player 1', 'Set 1 — hráč 2': 'Set 1 — player 2', 'Set 2 — hráč 1': 'Set 2 — player 1', 'Set 2 — hráč 2': 'Set 2 — player 2', 'Set 3 — hráč 1': 'Set 3 — player 1', 'Set 3 — hráč 2': 'Set 3 — player 2', 'Dátum': 'Date', 'Spoluhráč': 'Teammate', 'Súperi': 'Opponents', 'Set 1 (napr. 6-4)': 'Set 1 (e.g. 6-4)', 'Set 2 (napr. 3-6)': 'Set 2 (e.g. 3-6)', 'Set 3 (voliteľný)': 'Set 3 (optional)', 'Po odoslaní bude výsledok čakať na schválenie druhou dvojicou.': 'After submission, the result will wait for approval by the other pair.',
  'Tvoj profil sa nepodarilo nájsť podľa e-mailu.': 'Could not find your profile by email.', 'Hráči v zápase musia byť odlišní.': 'Players in a match must be different.', 'Dátum zápasu nie je platný.': 'The match date is not valid.', 'Výsledok zápasu sa nepodarilo uložiť.': 'Could not save the match result.', 'Hráč nie je prepojený s platným profilom v proffiles.': 'The player is not linked to a valid profile.', 'Štatistiky zápasu sa nepodarilo aktualizovať.': 'Could not update the match statistics.',

  // Challenges
  'Vyzvi súpera a dohodni si ligový zápas.': 'Challenge an opponent and arrange a league match.', 'Vytvoriť novú výzvu': 'Create new challenge', 'Všetky': 'All', 'Odoslané výzvy': 'Sent challenges', 'Dohodnuté zápasy': 'Agreed matches', 'Zatiaľ nemáš žiadne aktívne výzvy': 'You have no active challenges yet', 'Vyzvi hráča z rebríčka alebo vytvor novú výzvu na odohranie ligového zápasu.': 'Challenge a player from the rankings or create a new challenge to play a league match.', 'Zrušiť výzvu': 'Cancel challenge', 'Vytvoriť výzvu': 'Create challenge', 'Preferovaná aréna': 'Preferred arena', 'Navrhovaný dátum a čas': 'Proposed date and time', 'Správa pre súpera': 'Message for opponent', 'Odoslať výzvu': 'Send challenge', 'ODOSLANÁ': 'SENT', 'POTVRDENÁ': 'CONFIRMED', 'Meno hráča': 'Player name',

  // Profile
  'Osobné údaje': 'Personal details', 'Meno:': 'Name:', 'Telefón:': 'Phone:', 'Dátum registrácie:': 'Registration date:', 'Štatistiky ELO': 'ELO statistics', 'Aktuálne ELO:': 'Current ELO:', 'ELO od registrácie:': 'ELO since registration:', 'Najvyššie ELO:': 'Highest ELO:', 'Aktuálna sezóna:': 'Current season:', 'ELO od registrácie': 'ELO since registration', 'Krajská pozícia:': 'Regional position:', 'Celoslovenská pozícia:': 'National position:', '1. miesto': '1st place',
  'Štatistiky zápasov': 'Match statistics', 'Odohraté zápasy': 'Matches played', 'Celkový počet zápasov': 'Total number of matches', 'Výhry': 'Wins', 'Vyhraté zápasy': 'Matches won', 'Prehry': 'Losses', 'Ostatné zápasy': 'Other matches', 'Úspešnosť': 'Win rate', 'Vyhraté sety': 'Sets won', 'Prehraté sety': 'Sets lost', 'Vyhraté gemy': 'Games won', 'Prehraté gemy': 'Games lost', 'Celkový počet': 'Total',
  'Výsledky': 'Results', 'História zápasov': 'Match history', 'záznamov': 'records', 'Zápas čaká na potvrdenie': 'Match awaiting confirmation', '/2 dvojíc': '/2 pairs', 'Potvrdiť výsledok': 'Confirm result', 'Nahlásiť chybu': 'Report error', 'Načítavam históriu zápasov…': 'Loading match history…', 'Históriu zápasov sa nepodarilo načítať.': 'Could not load match history.', 'Zatiaľ nemáš žiadne odohraté zápasy.': "You haven't played any matches yet.", 'Po odohraní zápasu sa jeho výsledok zobrazí tu.': 'After you play a match, its result will appear here.', 'Súper:': 'Opponent:', 'VÝHRA': 'WIN', 'PREHRA': 'LOSS', 'Aktuálna séria': 'Current streak', 'Výhra': 'Win', 'Prehra': 'Loss',
  'Upraviť dominantnú ruku': 'Edit dominant hand', 'Upraviť domovskú arénu': 'Edit home arena', 'Dominantná ruka:': 'Dominant hand:', 'Domovská aréna:': 'Home arena:', 'Automaticky podľa najnavštevovanejšieho klubu': 'Automatically based on the most visited club', 'Zväčšiť profilovú fotografiu': 'Enlarge profile photo', 'Profilová fotografia': 'Profile photo', 'Vyber arénu': 'Select arena', 'Zadať zápas': 'Enter match',
  'Domovskú arénu sa nepodarilo uložiť.': 'Could not save the home arena.', 'Dominantnú ruku sa nepodarilo uložiť.': 'Could not save the dominant hand.',

  // Rankings
  'SPL / REBRÍČKY': 'SPL / RANKINGS', 'Poradie hráčov podľa ELO a arén, ktoré navštevujú.': 'Players ranked by ELO and the arenas they visit.', 'Celoslovenský rebríček': 'National ranking', 'Krajský rebríček': 'Regional ranking', 'Rebríček arén': 'Arena ranking', 'Vybrať arénu': 'Select arena', 'Filtrovať kraj': 'Filter region', 'Arény sa nepodarilo načítať.': 'Could not load arenas.', 'Načítavam rebríček…': 'Loading ranking…', 'Najprv vyber arénu.': 'Select an arena first.', 'V tomto rebríčku sa nenašli hráči.': 'No players were found in this ranking.', 'Typ rebríčka': 'Ranking type', 'Pozícia': 'Position', 'HRÁČ': 'PLAYER', 'ELO Rating': 'ELO rating', 'Odohrané zápasy': 'Matches played', 'Poradie hráčov podľa dynamického ELO ratingu.': 'Players ranked by dynamic ELO rating.', 'Aktualizované po potvrdení zápasu': 'Updated after match confirmation', 'Vyber kraj ': 'Select region',

  // Arenas
  'Všetky mestá': 'All cities', 'Partnerské arény ligy SPL. Nájdi svoj domovský klub a rezervuj si kurt.': 'Partner arenas of the SPL league. Find your home club and book a court.', 'Hľadať arénu, mesto alebo adresu': 'Search arena, city or address', 'Mesto': 'City', 'Zobrazené arény': 'Arenas shown', 'Načítavam arény…': 'Loading arenas…', 'Arény sa nepodarilo načítať. Skontroluj tabuľku arenas v Supabase.': 'Could not load arenas. Check the arenas table in Supabase.', 'Zatiaľ žiadne partnerské arény': 'No partner arenas yet', 'V tomto výbere nie je žiadna aréna': 'There are no arenas in this selection', 'Liga práve pripravuje spoluprácu s arénami. Prvé kluby sa tu zobrazia čoskoro.': 'The league is currently preparing partnerships with arenas. The first clubs will appear here soon.', 'Skús iné mesto alebo vyhľadávanie.': 'Try a different city or search.', 'Tvoj domovský klub': 'Your home club', 'Počet kurtov': 'Number of courts', 'Otváracie hodiny': 'Opening hours', 'Víkend': 'Weekend', 'Vytvoriť výzvu tu': 'Create a challenge here', 'Nastaviť ako domov': 'Set as home',

  // Pairs and pair challenges
  'Vyber súperiacu dvojicu vo svojom okolí a navrhni termín zápasu.': 'Choose an opposing pair near you and propose a match date.', 'Pridať dvojicu': 'Add pair', 'Dvojica': 'Pair', 'dvojíc': 'pairs', 'Dvojice sa nepodarilo načítať.': 'Could not load pairs.', 'Načítavam dvojice…': 'Loading pairs…', 'Aby si mohol vyzývať, najprv si vytvor dvojicu so spoluhráčom.': 'To challenge others, first create a pair with a teammate.', 'Žiadne dvojice v tomto kraji.': 'No pairs in this region.', 'Priem. ELO': 'Avg. ELO', 'Moje výzvy': 'My challenges', 'Zatiaľ si neodoslal žiadnu výzvu.': "You haven't sent any challenges yet.", 'Prihlás sa, aby si mohol vyzývať dvojice.': 'Log in to challenge pairs.', 'Výzva bola odoslaná.': 'Challenge sent.', 'Najprv si vytvor dvojicu so spoluhráčom.': 'First create a pair with a teammate.', 'Každý hráč v zápase musí byť odlišný.': 'Every player in a match must be different.', 'Termín musí byť v budúcnosti.': 'The date must be in the future.', 'Výzvu sa nepodarilo uložiť.': 'Could not save the challenge.', 'Výzvu sa nepodarilo zrušiť.': 'Could not cancel the challenge.', 'Tvoja dvojica': 'Your pair', 'Dátum zápasu': 'Match date', 'Čas zápasu': 'Match time', 'Odosielam…': 'Sending…', 'Čaká na odpoveď': 'Awaiting response', 'Prijatá': 'Accepted', 'Odmietnutá': 'Declined', 'Zrušená': 'Cancelled',
  'Vyber oboch hráčov.': 'Select both players.', 'Hráči v dvojici musia byť odlišní.': 'Players in a pair must be different.', 'Dvojicu sa nepodarilo uložiť.': 'Could not save the pair.', 'Späť na výzvu': 'Back to challenge', 'Dvojice': 'Pairs', 'Vyhľadať dvojicu': 'Search pair', 'Vyhľadať hráča v dvojici': 'Search player in pair', 'Zatiaľ nie sú vytvorené žiadne dvojice.': 'No pairs have been created yet.', 'Žiadna dvojica nezodpovedá vyhľadávaniu.': 'No pair matches the search.', 'Túto dvojicu nemôžeš vyzvať.': 'You cannot challenge this pair.', 'Vaša dvojica': 'Your pair', 'Vyber hráča': 'Select player', 'Ukladám…': 'Saving…', 'Uložiť dvojicu': 'Save pair',

  // Tournaments
  'Overujem prístup…': 'Checking access…', 'Overenie účtu': 'Account verification', 'Potvrď svoj e-mail': 'Confirm your email', 'Turnaje sú dostupné po potvrdení e-mailovej adresy.': 'Tournaments are available after your email address is confirmed.', 'Späť na prihlásenie': 'Back to login', 'SPL podujatia': 'SPL events', 'Hraj o trofeje, ELO body a miesto medzi najlepšími hráčmi Slovenska.': 'Play for trophies, ELO points and a place among the best players in Slovakia.', 'Nadchádzajúce turnaje': 'Upcoming tournaments', 'Moje turnaje': 'My tournaments', 'Ukončené turnaje': 'Completed tournaments',
  'Odhlásiť sa z turnaja?': 'Withdraw from the tournament?', 'Tvoja dvojica bude odstránená z kapacity turnaja.': 'Your pair will be removed from the tournament capacity.', 'Zobraziť nadchádzajúce turnaje': 'View upcoming tournaments', 'Štartovné': 'Entry fee', 'Ceny & ELO': 'Prizes & ELO', 'Obsadenosť': 'Capacity', 'Prihlásiť sa na turnaj': 'Register for the tournament', 'Prihlásenie na turnaj': 'Tournament registration', 'Tvoj spoluhráč': 'Your teammate', 'Tvoj spoluhráč:': 'Your teammate:', 'Vyber registrovaného hráča': 'Select a registered player', 'Hosťujúci spoluhráč': 'Guest teammate', 'Meno hosťa': 'Guest name', 'Telefón hosťa': 'Guest phone', 'Poznámka / preferencie': 'Note / preferences', 'Súhlasím s podmienkami turnaja a beriem na vedomie úhradu štartovného na mieste.': 'I agree to the tournament terms and acknowledge that the entry fee is paid on site.', 'Potvrdiť prihlášku': 'Confirm registration', 'Schválené': 'Approved',
  'PRIHLASOVANIE OTVORENÉ': 'REGISTRATION OPEN', 'OBSADENÉ': 'FULL', 'PREBIEHA': 'IN PROGRESS', 'UKONČENÝ': 'COMPLETED', 'Zatiaľ nie si prihlásený na žiadny turnaj': "You aren't registered for any tournament yet", 'Momentálne nie sú naplánované žiadne turnaje': 'There are currently no scheduled tournaments', 'Zatiaľ neboli odohraté žiadne turnaje': 'No tournaments have been played yet', 'Prezri si nadchádzajúce turnaje v tvojom kraji, nájdi spoluhráča a bojuj o trofeje a ELO body do rebríčka SPL.': 'Browse upcoming tournaments in your region, find a teammate and compete for trophies and ELO points in the SPL ranking.', 'Turnaje sa zobrazia hneď, ako budú dostupné.': 'Tournaments will appear as soon as they are available.',
}

export const uiPatterns: Array<[RegExp, string]> = [
  [/^(\d+) záznamov$/, '$1 records'],
  [/^Meno hráča (\d+)$/, 'Player $1 name'],
  [/^Vyplň mená všetkých (\d+) zúčastnených hráčov\.$/, 'Fill in the names of all $1 participating players.'],
  [/^Forma v posledných (\d+) odohratých zápasoch, od najstaršieho po najnovší$/, 'Form in the last $1 played matches, from oldest to newest'],
  [/^(.+) ti poslal\(a\) žiadosť o priateľstvo\.$/, '$1 sent you a friend request.'],
  [/^Chyba pri vytváraní inzerátu: (.*)$/, 'Error creating the listing: $1'],
  [/^Chyba pri odosielaní správy: (.*)$/, 'Error sending the message: $1'],
  [/^Profil „(.+)“ neexistuje alebo meno nie je jednoznačné\.$/, 'Profile “$1” does not exist or the name is ambiguous.'],
  [/^(\d+) \/ (\d+) dvojíc$/, '$1 / $2 pairs'],
  [/^(\d+)\. miesto$/, '#$1'],
]
