create table if not exists public.pair_invitations (
  id bigint generated by default as identity primary key,
  inviter_id bigint not null references public.proffiles(id) on delete cascade,
  invitee_id bigint not null references public.proffiles(id) on delete cascade,
  status text not null default 'pending' check (status in ('pending', 'accepted', 'declined')),
  created_at timestamptz not null default now(),
  check (inviter_id <> invitee_id)
);

create index if not exists pair_invitations_invitee_status_idx
  on public.pair_invitations (invitee_id, status, created_at desc);

create unique index if not exists pair_invitations_pending_pair_idx
  on public.pair_invitations (least(inviter_id, invitee_id), greatest(inviter_id, invitee_id))
  where status = 'pending';

alter table public.pair_invitations enable row level security;
grant select on public.pair_invitations to authenticated;
revoke insert on public.pairs from anon, authenticated;

drop policy if exists "pair invitation participants can read" on public.pair_invitations;
create policy "pair invitation participants can read" on public.pair_invitations
  for select to authenticated
  using (
    exists (
      select 1
      from public.proffiles as profile
      where profile.id in (inviter_id, invitee_id)
        and lower(profile.email) = lower(auth.jwt() ->> 'email')
    )
  );

create or replace function public.create_pair_invitation(p_invitee_id bigint)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  current_profile_id bigint;
  invitation_id bigint;
begin
  if auth.uid() is null then
    raise exception 'Prihlásenie je potrebné na pozvanie do dvojice.';
  end if;

  select profile.id
  into current_profile_id
  from public.proffiles as profile
  where lower(profile.email) = lower(auth.jwt() ->> 'email')
  limit 1;

  if current_profile_id is null then
    raise exception 'Profil prihláseného používateľa sa nenašiel.';
  end if;

  if p_invitee_id is null or p_invitee_id = current_profile_id then
    raise exception 'Vyber iného hráča.';
  end if;

  if not exists (
    select 1
    from public.friendships as friendship
    where friendship.status = 'accepted'
      and (
        (friendship.user_id = current_profile_id and friendship.friend_id = p_invitee_id)
        or (friendship.user_id = p_invitee_id and friendship.friend_id = current_profile_id)
      )
  ) then
    raise exception 'Pozvať do dvojice môžeš iba prijatého priateľa.';
  end if;

  if exists (
    select 1
    from public.pairs as pair
    where (pair.player_1_id = current_profile_id and pair.player_2_id = p_invitee_id)
      or (pair.player_1_id = p_invitee_id and pair.player_2_id = current_profile_id)
  ) then
    raise exception 'Títo hráči už tvoria dvojicu.';
  end if;

  insert into public.pair_invitations (inviter_id, invitee_id)
  values (current_profile_id, p_invitee_id)
  returning id into invitation_id;

  return invitation_id;
end;
$$;

create or replace function public.respond_to_pair_invitation(p_invitation_id bigint, p_accept boolean)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  current_profile_id bigint;
  invitation_inviter_id bigint;
begin
  if auth.uid() is null then
    raise exception 'Prihlásenie je potrebné na odpoveď na pozvanie.';
  end if;

  select profile.id
  into current_profile_id
  from public.proffiles as profile
  where lower(profile.email) = lower(auth.jwt() ->> 'email')
  limit 1;

  if current_profile_id is null then
    raise exception 'Profil prihláseného používateľa sa nenašiel.';
  end if;

  select invitation.inviter_id
  into invitation_inviter_id
  from public.pair_invitations as invitation
  where invitation.id = p_invitation_id
    and invitation.invitee_id = current_profile_id
    and invitation.status = 'pending'
  for update;

  if invitation_inviter_id is null then
    raise exception 'Čakajúce pozvanie sa nenašlo.';
  end if;

  if not p_accept then
    update public.pair_invitations
    set status = 'declined'
    where id = p_invitation_id;
    return;
  end if;

  if not exists (
    select 1
    from public.friendships as friendship
    where friendship.status = 'accepted'
      and (
        (friendship.user_id = current_profile_id and friendship.friend_id = invitation_inviter_id)
        or (friendship.user_id = invitation_inviter_id and friendship.friend_id = current_profile_id)
      )
  ) then
    raise exception 'Dvojicu môžu vytvoriť iba prijatí priatelia.';
  end if;

  if exists (
    select 1
    from public.pairs as pair
    where (pair.player_1_id = current_profile_id and pair.player_2_id = invitation_inviter_id)
      or (pair.player_1_id = invitation_inviter_id and pair.player_2_id = current_profile_id)
  ) then
    raise exception 'Títo hráči už tvoria dvojicu.';
  end if;

  insert into public.pairs (player_1_id, player_2_id)
  values (invitation_inviter_id, current_profile_id);

  update public.pair_invitations
  set status = 'accepted'
  where id = p_invitation_id;
end;
$$;

revoke all on function public.create_pair_invitation(bigint) from public;
revoke all on function public.respond_to_pair_invitation(bigint, boolean) from public;
grant execute on function public.create_pair_invitation(bigint) to authenticated;
grant execute on function public.respond_to_pair_invitation(bigint, boolean) to authenticated;

do $$
begin
  if exists (select 1 from pg_publication where pubname = 'supabase_realtime')
    and not exists (
      select 1
      from pg_publication_tables
      where pubname = 'supabase_realtime'
        and schemaname = 'public'
        and tablename = 'pair_invitations'
    ) then
    alter publication supabase_realtime add table public.pair_invitations;
  end if;
end;
$$;
